<!DOCTYPE html>
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
    <title>Code-Struction</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="/website/images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="/website/images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/website/css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="/website/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/website/css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/website/css/custom.css">
	<script src="/website/js/modernizr.js"></script> <!-- Modernizr -->

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body id="page-top" class="politics_version">

    <!-- LOADER -->
    <div id="preloader">
        <div id="main-ld">
			<div id="loader"></div>  
		</div>
    </div><!-- end loader -->
    <!-- END LOADER -->
	
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
			<img class="img-fluid" id="homeLogo" src="/images/logo/homeLogo.png" alt="" />
		</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger active" href="#home">Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#testimonials">Testimonials</a>
            </li>
              <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#about">About Us</a>
              </li>
			<li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact Us</a>
            </li>
              <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" id="navLoginLink" href="/login">Login</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>

	<section id="home" class="main-banner parallaxie" style="background: url(https://wallpapercave.com/wp/wp1842341.jpg)">
		<div class="heading">
			<h1>Engineering your dreams with us</h1>
			<p>"Building the future. <br>  Restoring the past."</p>
			<h3 class="cd-headline clip is-full-width">
                <span>Leave the</span>
                <span class="cd-words-wrapper">
					<b class="is-visible">Painting</b>
					<b>Plumbing</b>
					<b>Insulation</b>
					<b>Electrics</b>
					<b>Solar Panels</b>
					<b>Fire Places</b>
					<b>Swimming Pools</b>
                    <b>Ceilings</b>
                    <b>Ceramic Flooring</b>
                    <b>Frames</b>
				</span>
                <span>to the professionals.</span>

            </h3>
		</div>
	</section>

    <div id="services" class="section lb">
        <div class="container">
            <div class="section-title text-left">
                <h3>Services</h3>
                <p>Trust is just one of the things we build well.</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-seo"></i>
                        </div>
                        <h2>Virtual Construction</h2>
                        <p>The Project Team will develop a strategy where Building Information Modeling (BIM) or Virtual Design & Construction (VDC)
                            can be implemented in order to mitigate risk to the project’s budget or schedule.
                        </p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-development"></i>
                        </div>
                        <h2>Design-Build</h2>
                        <p>
                            Our collaborative approach to Design-Build brings the design firm and the subcontractors together in a focused, team-oriented relationship offering Owners a single source of contact and responsibility.
                        </p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-process"></i>
                        </div>
                        <h2>Pre-Construction Services</h2>
                        <p>Our preconstruction services include design review, constructability analysis, value engineering, as well as detailed, accurate and easy to understand estimates.</p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-discuss-issue"></i>
                        </div>
                        <h2>Support</h2>
                        <p>Our technical service and support are unmatched in the industry. We can help you with any one of the following state-of-the-art technical services. Please use our Service Inquiry Form to contact us regarding any of our services. We can help! </p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-idea"></i>
                        </div>
                        <h2>Energy Profit</h2>
                        <p>Energy retrofit of a building includes a series of activities that aim the reduction of the operating costs of a building for both heating and cooling.
                            Includes external solid wall insulation, roof insulation, doors and windows frames replacements.</p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="services-inner-box">
                        <div class="ser-icon">
                            <i class="flaticon-idea-1"></i>
                        </div>
                        <h2>Extensive Renovation</h2>
                        <p>We undertake every renovation project that may either include minor changes to upgrade and modernize your residence or office that will provide the owner a major quality, safety and aesthetic upgrade.</p>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

	<div id="portfolio" class="section lb">
		<div class="container">
			<div class="section-title text-left">
                <h3>Portfolio</h3>
                <p>Excellence is not an act but a habit.</p>
            </div><!-- end title -->

			<div class="gallery-menu row">
				<div class="col-md-12">
					<div class="button-group filter-button-group text-left">
						<button class="active" data-filter="*">All</button>
						<button data-filter=".gal_a">Interior</button>
						<button data-filter=".gal_b">Exterior</button>
					</div>
				</div>
			</div>

			<div class="gallery-list row">
				<div class="col-md-4 col-sm-6 gallery-grid gal_a">
					<div class="gallery-single fix">
						<img src="http://www.bgc.com.au/assets/bgc/img/photos/bgc-plumbing-under-floor-heating-install.jpg" class="img-fluid" alt="Image">
						<div class="img-overlay">
							<a href="http://www.bgc.com.au/assets/bgc/img/photos/bgc-plumbing-under-floor-heating-install.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
						</div>
					</div>
				</div>

                <div class="col-md-4 col-sm-6 gallery-grid gal_b">
                    <div class="gallery-single fix">
                        <img src="https://solarsite.net/wp-content/uploads/2019/09/e2808esolar-panel-installation.jpg" class="img-fluid" alt="Image">
                        <div class="img-overlay">
                            <a href="https://solarsite.net/wp-content/uploads/2019/09/e2808esolar-panel-installation.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
                        </div>
                    </div>
                </div>

				<div class="col-md-4 col-sm-6 gallery-grid gal_a">
					<div class="gallery-single fix">
						<img src="https://certapro.com/wp-content/themes/certapro/landing-templates/img/service-interior.jpg" class="img-fluid" alt="Image">
						<div class="img-overlay">
							<a href="https://certapro.com/wp-content/themes/certapro/landing-templates/img/service-interior.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
						</div>
					</div>
				</div>

				<div class="col-md-4 col-sm-6 gallery-grid gal_a">
					<div class="gallery-single fix">
						<img src="https://media.istockphoto.com/videos/construction-construction-work-with-ceramic-floor-tiles-video-id903004104?s=640x640" class="img-fluid" alt="Image">
						<div class="img-overlay">
							<a href="https://media.istockphoto.com/videos/construction-construction-work-with-ceramic-floor-tiles-video-id903004104?s=640x640" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
						</div>
					</div>
				</div>

                <div class="col-md-4 col-sm-6 gallery-grid gal_b">
                    <div class="gallery-single fix">
                        <img src="https://www.houselogic.com/wp-content/uploads/2011/03/exterior-house-painting-epspainting-standard_c231db00f6cd6e9389489e72c0f32fe0.jpg?crop&resize=3200%2C2134" class="img-fluid" alt="Image">
                        <div class="img-overlay">
                            <a href="https://www.houselogic.com/wp-content/uploads/2011/03/exterior-house-painting-epspainting-standard_c231db00f6cd6e9389489e72c0f32fe0.jpg?crop&resize=3200%2C2134" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
                        </div>
                    </div>
                </div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_a">
                <div class="gallery-single fix">
                    <img src="https://media.istockphoto.com/photos/domestic-electrical-work-picture-id624155076?k=6&m=624155076&s=612x612&w=0&h=MyZw1sOVRw5Y0j0yO_X1M76-pHqETbJIxDnQfpy4hc4=" class="img-fluid" alt="Image">
                    <div class="img-overlay">
                        <a href="https://media.istockphoto.com/photos/domestic-electrical-work-picture-id624155076?k=6&m=624155076&s=612x612&w=0&h=MyZw1sOVRw5Y0j0yO_X1M76-pHqETbJIxDnQfpy4hc4=" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_b">
					<div class="gallery-single fix">
						<img src="https://homeproconnections.com/images/svcs/Pool%20Resurfacing.jpg" class="img-fluid" alt="Image">
						<div class="img-overlay">
							<a href="https://homeproconnections.com/images/svcs/Pool%20Resurfacing.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
						</div>
					</div>
			</div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_a">
                <div class="gallery-single fix">
                    <img src="https://tzakas-hellas.gr/wp-content/uploads/2018/05/maxresdefault.jpg" class="img-fluid" alt="Image">
                    <div class="img-overlay">
                        <a href="https://tzakas-hellas.gr/wp-content/uploads/2018/05/maxresdefault.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6 gallery-grid gal_b">
					<div class="gallery-single fix">
						<img src="https://easyfixnashville.com/wp-content/uploads/2019/11/fence-borrow-min.jpg" class="img-fluid" alt="Image">
						<div class="img-overlay">
							<a href="https://easyfixnashville.com/wp-content/uploads/2019/11/fence-borrow-min.jpg" data-rel="prettyPhoto[gal]" class="hoverbutton global-radius"><i class="fa fa-picture-o"></i></a>
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	</div>

	 <div id="testimonials" class="section wb">
        <div class="container">
            <div class="section-title text-left">
                <h3>Testimonials</h3>
                <p>Thanks for all your awesome testimonials! There are hundreds of happy customers! </p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="testi-carousel owl-carousel owl-theme">
                        <div class="testimonial clearfix">
                            <div class="desc">
                                <h3><i class="fa fa-quote-left"></i> Wonderful Support!</h3>
                                <p class="lead">They have got my project on time with the competition with a sed highly skilled, and experienced & professional team.</p>
                            </div>
                            <div class="testi-meta">
                                <img src="/website/uploads/testi_01.png" alt="" class="img-fluid alignleft">
                                <h4>James Fernando <small>- Manager of Racer</small></h4>
                            </div>
                            <!-- end testi-meta -->
                        </div>
                        <!-- end testimonial -->

                        <div class="testimonial clearfix">
                            <div class="desc">
                                <h3><i class="fa fa-quote-left"></i> Awesome Services!</h3>
                                <p class="lead">Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you completed.</p>
                            </div>
                            <div class="testi-meta">
                                <img src="/website/uploads/testi_02.png" alt="" class="img-fluid alignleft">
                                <h4>Jacques Philips <small>- Designer</small></h4>
                            </div>
                            <!-- end testi-meta -->
                        </div>
                        <!-- end testimonial -->


                        <div class="testimonial clearfix">
                            <div class="desc">
                                <h3><i class="fa fa-quote-left"></i> Wonderful Support!</h3>
                                <p class="lead">They have got my project on time with the competition with a sed highly skilled, and experienced & professional team.</p>
                            </div>
                            <div class="testi-meta">
                                <img src="/website/uploads/testi_01.png" alt="" class="img-fluid alignleft">
                                <h4>James Fernando <small>- Manager of Racer</small></h4>
                            </div>
                            <!-- end testi-meta -->
                        </div>
                        <!-- end testimonial -->

                        <div class="testimonial clearfix">
                            <div class="desc">
                                <h3><i class="fa fa-quote-left"></i> Awesome Services!</h3>
                                <p class="lead">Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you completed.</p>
                            </div>
                            <div class="testi-meta">
                                <img src="/website/uploads/testi_02.png" alt="" class="img-fluid alignleft">
                                <h4>Jacques Philips <small>- Designer</small></h4>
                            </div>
                            <!-- end testi-meta -->
                        </div>
                        <!-- end testimonial -->

                        <div class="testimonial clearfix">
                            <div class="desc">
                                <h3><i class="fa fa-quote-left"></i> Great & Talented Team!</h3>
                                <p class="lead">The master-builder of human happines no one rejects, dislikes avoids pleasure itself, because it is very pursue pleasure. </p>
                            </div>
                            <div class="testi-meta">
                                <img src="/website/uploads/testi_03.png" alt="" class="img-fluid alignleft">
                                <h4>Venanda Mercy <small>- Athens, Greece</small></h4>
                            </div>
                            <!-- end testi-meta -->
                        </div><!-- end testimonial -->
                    </div><!-- end carousel -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div id="about" class="section wb">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="message-box">
                        <h2>About Code-Struction</h2>
                        <p>For over 30 years, commitment to our Core Values has made Code-Struction the ideal building partner for the region’s most forward-thinking organizations.</p>
                        <p>Our success comes from a steadfast commitment to the client’s vision and a culture of balance, integrity, leadership and loyalty. At Code-Struction, we transform the construction experience through creation of an environment that fosters collaboration and project team engagement.</p>
                        <p>With a workplace that attracts and retains the best employees in every field. We are proud of the dedication, skill, and integrity of each of our employees, and their unique contributions in building our high-performance teams.</p>

                        <a href="/login" class="sim-btn btn-hover-new" data-text="Now"><span>Login</span></a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="right-box-pro wow fadeIn">
                        <img src="https://cif.ie/wp-content/uploads/2018/11/King-Moffatt-Headquarters-Aerial-1.jpg" alt="" class="img-fluid img-rounded">
                    </div><!-- end media -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div id="contact" class="section db">
        <div class="container">
            <div class="section-title text-left">
                <h3>Contact</h3>
                <p>El. Venizelou 154 & Romylias - Kastri N. Erythrea, PC 146 71</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="contact_form">
                        <iframe width="797" height="513" id="gmap_canvas" src="https://maps.google.com/maps?q=excelixi%20kastri&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="
">
                        </iframe>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div class="copyrights">
        <div class="container">
            <div class="footer-distributed">
                <div class="footer-left">
                    <p class="footer-links">
                        <a href="#">Privacy policy</a>
                        <a href="#">Terms of use</a>
                        <a href="#about">About</a>
                        <a href="#contact">Contact</a>
                    </p>
                    <p class="footer-company-name">All Rights Reserved. &copy; 2019 <a href="#">Code-Struction </a> Design By :
					<a href="https://gitlab.com/project-future-team-2">Project-future team #2</a></p>
                </div>
            </div>
        </div><!-- end container -->
    </div><!-- end copyrights -->

    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="/website/js/all.js"></script>
	<!-- Camera Slider -->
	<script src="js/jquery.mobile.customized.min.js"></script>
	<script src="/website/js/jquery.easing.1.3.js"></script>
	<script src="/website/js/parallaxie.js"></script>
	<script src="/website/js/headline.js"></script>
	<!-- Contact form JavaScript -->
    <script src="/website/js/jqBootstrapValidation.js"></script>
    <script src="/website/js/contact_me.js"></script>
    <!-- ALL PLUGINS -->
    <script src="/website/js/custom.js"></script>
    <script src="/website/js/jquery.vide.js"></script>

</body>
</html>